os:
  - linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

language: node_js
node_js:
  - "lts/*"
  - "stable"

install:
  - export CXX=g++-4.8
  - $CXX --version
  - npm i

before_install:
  - npm install -g node-gyp
  - rm -rf ~/.node-gyp/

script:
  - npm run lint
  - npm run test-travis

after_script:
  - npm install coveralls@2 && cat ./coverage/lcov.info | coveralls
